
# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED

        sliding-window-size: 10 # Close ????, ?? ??? ??? ???? ?? ???? ????. (?? 10? ? 3? ???? 30%)
        minimum-number-of-calls: 10 # Close ????, sliding window ? ?? ??? open ??? ?? ???????. sliding window ??? ?? ?? try ?? ??? ???. (9 ? ?? ???? 10 ?? try ? close ??? ????.)

        permitted-number-of-calls-in-half-open-state: 5 # Half-open ????, ?? ??? ??? ???? ?? ???? ????. (Half-open ????? sliding window size)

        failure-rate-threshold: 40 # Close ???? Open, Half-open ???? Open ?? ???? ??? ???

        slow-call-duration-threshold: 3000 # ???? ??? ???? timeout ???
        slow-call-rate-threshold: 60 # Close ???? Open, Half-open ???? Open ?? ???? ???? ??? ???

        automatic-transition-from-open-to-half-open-enabled: true # Open ????, Half-open ??? ?? ????? ??? ???? ????? ??.
        wait-duration-in-open-state: 10000 # Open ????, Half-open ??? ???? ??? ????(ms)

    instances:
      myCircuitBreakerConfig:
        base-config: default
